### ISSUE TITLE
How to set some parameters in RNA-seq test data

### ISSUE THREAD

**Issue by lh12565** [HuangLabUMN/oncoPredict#1]
Hi, I have a RNA-seq log2(TPM+1) data. I want to use GDSC2 data for train and  log2(TPM+1) for test to prediction. My parameters like below:
```
batchCorrect="standardize"
removeLowVaringGenesFrom="rawData"
```
Are my parameters correct? Do other default parameters need to be changed? Thanks!

**Comment by HuangLabUMN** [comment]
In general we recommend 'standardize' when you use microarray training data to build models on RNA-seq testing data. Additionally, 'removeLowVaringGenes' is by default set to 0.2 and determines the percentage of low varying genes to remove; I recommend plotting the percentage of low varying genes in your dataset to customize this parameter.
